// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: delete_todo.proto at 3:1
package com.example.daniele.proto.todo;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class DeleteTodo extends Message<DeleteTodo, DeleteTodo.Builder> {
  public static final ProtoAdapter<DeleteTodo> ADAPTER = new ProtoAdapter_DeleteTodo();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ID = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String id;

  public DeleteTodo(String id) {
    this(id, ByteString.EMPTY);
  }

  public DeleteTodo(String id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DeleteTodo)) return false;
    DeleteTodo o = (DeleteTodo) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(id, o.id);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    return builder.replace(0, 2, "DeleteTodo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<DeleteTodo, Builder> {
    public String id;

    public Builder() {
    }

    public Builder id(String id) {
      this.id = id;
      return this;
    }

    @Override
    public DeleteTodo build() {
      if (id == null) {
        throw Internal.missingRequiredFields(id, "id");
      }
      return new DeleteTodo(id, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_DeleteTodo extends ProtoAdapter<DeleteTodo> {
    ProtoAdapter_DeleteTodo() {
      super(FieldEncoding.LENGTH_DELIMITED, DeleteTodo.class);
    }

    @Override
    public int encodedSize(DeleteTodo value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, DeleteTodo value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public DeleteTodo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public DeleteTodo redact(DeleteTodo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
